# Generated by Django 5.0.4 on 2024-08-31 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0003_alter_ambulatoryhistory_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesshistory',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_history_diagnosis', to='sanatorium.diagnosistemplate'),
        ),
        migrations.AlterField(
            model_name='illnesshistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_history_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
