# Generated by Django 5.0.4 on 2024-09-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_nurseaccountmodel'),
        ('sanatorium', '0004_alter_illnesshistory_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesshistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='illness_history_doctor', to='account.doctoraccountmodel'),
        ),
        migrations.AlterField(
            model_name='illnesshistory',
            name='nurse',
            field=models.ManyToManyField(related_name='illness_history_nurse', to='account.nurseaccountmodel'),
        ),
    ]
