# Generated by Django 5.0.4 on 2024-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0005_alter_illnesshistory_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialappointmentwithdoctormodel',
            name='ill_part_stomach',
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='arterial_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='arterial_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='extra_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='heart_beat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='imt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='respiratory_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
