# Generated by Django 5.0.4 on 2024-09-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0007_remove_basepillsinjectionsmodel_model_ref_id_and_more'),
        ('warehouse', '0041_remove_expenseitemsmodel_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepillsinjectionsmodel',
            name='pills_injections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.itemsinstockmodel'),
        ),
        migrations.AlterField(
            model_name='basepillsinjectionsmodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
