# Generated by Django 5.0.4 on 2024-09-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0010_alter_baseprocedureservicemodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselabresearchservicemodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
