# Generated by Django 5.0.4 on 2024-09-29 16:46

import apps.lis.models.containers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0011_alter_baselabresearchservicemodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalappointmentwithdoctormodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.lis.models.containers.upload_location),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='arterial_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='arterial_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='heart_beat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='imt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='imt_interpretation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
