# Generated by Django 5.0.4 on 2024-09-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0013_finalappointmentwithdoctormodel_arterial_high_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='arterial_high_low',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
