# Generated by Django 5.1.1 on 2024-10-05 07:49

import apps.lis.models.containers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0014_alter_finalappointmentwithdoctormodel_arterial_high_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingwithcardiologistmodel',
            name='arterial_high_low',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultingwithcardiologistmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.lis.models.containers.upload_location),
        ),
    ]
