# Generated by Django 5.1.1 on 2024-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0017_alter_appointmentwithondutydoctormodel_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentwithondutydoctoronarrivalmodel',
            name='arterial_high_low',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
