# Generated by Django 5.1.1 on 2024-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0018_appointmentwithondutydoctoronarrivalmodel_arterial_high_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentwithondutydoctoronarrivalmodel',
            name='temperature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
