# Generated by Django 5.1.1 on 2024-10-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0021_alter_repeatedappointmentwithdoctormodel_imt'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentwithondutydoctormodel',
            name='arterial_high_low',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentwithondutydoctormodel',
            name='imt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
