# Generated by Django 5.1.1 on 2024-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0023_appointmentwithondutydoctormodel_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekgappointmentmodel',
            name='objective_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ekgappointmentmodel',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
