# Generated by Django 5.1.1 on 2024-10-16 18:07

import apps.lis.models.containers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_tg_username'),
        ('sanatorium', '0024_ekgappointmentmodel_objective_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to=apps.lis.models.containers.upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('base_lab_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='sanatorium.baselabresearchservicemodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_result_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_result_mdf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-result_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, default='dispatched', max_length=25, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modf_proc_tasks', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanatorium.baseprocedureservicemodel')),
                ('procedure_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.doctoraccountmodel')),
            ],
        ),
    ]
