# Generated by Django 5.1.1 on 2024-10-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0025_labresult_proceduretasksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresult',
            name='base_lab_research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='sanatorium.baselabresearchservicemodel'),
        ),
    ]
