# Generated by Django 5.1.1 on 2024-10-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0028_proceduredaysmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduredaysmodel',
            name='is_out_of_graphic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
