# Generated by Django 5.1.1 on 2024-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0030_baseprocedureservicemodel_done_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='file_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proceduredaysmodel',
            name='state',
            field=models.CharField(choices=[('создано', 'создано'), ('отменено', 'отменено'), ('приостановлено', 'приостановлено'), ('диспетчеризирован', 'диспетчеризирован'), ('выполнено', 'выполнено')], default='created', max_length=50),
        ),
    ]
