# Generated by Django 5.1.1 on 2024-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0031_labresult_file_format_alter_proceduredaysmodel_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basepillsinjectionsmodel',
            old_name='quantity',
            new_name='quantity_per_session',
        ),
        migrations.RemoveField(
            model_name='basepillsinjectionsmodel',
            name='pills_injections',
        ),
        migrations.RemoveField(
            model_name='basepillsinjectionsmodel',
            name='price',
        ),
        migrations.AlterField(
            model_name='basepillsinjectionsmodel',
            name='frequency',
            field=models.CharField(choices=[('3 раза в день', 3), ('до еды', 1), ('после еды', 1)], default='', max_length=50),
        ),
    ]
