# Generated by Django 5.1.1 on 2024-11-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0033_alter_illnesshistory_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemedicalservicemodel',
            name='illness_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_med_services', to='sanatorium.illnesshistory'),
        ),
        migrations.AlterField(
            model_name='baseprocedureservicemodel',
            name='illness_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_procedures', to='sanatorium.illnesshistory'),
        ),
    ]
