# Generated by Django 5.1.1 on 2025-01-02 11:10

import apps.lis.models.containers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0034_alter_basemedicalservicemodel_illness_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='illnesshistory',
            name='is_sick_leave',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.lis.models.containers.upload_lab_files_location),
        ),
    ]
