# Generated by Django 5.1.1 on 2025-04-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0036_alter_illnesshistory_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprocedureservicemodel',
            name='state',
            field=models.CharField(choices=[('recommended', 'recommended'), ('assigned', 'assigned'), ('cancelled', 'cancelled'), ('stopped', 'stopped'), ('dispatched', 'dispatched')], default='assigned', max_length=50),
        ),
    ]
