# Generated by Django 5.0.4 on 2024-08-04 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notificationmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='information_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.informationsourcemodel'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modf_patient_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.organizationmodel'),
        ),
    ]
