# Generated by Django 5.0.4 on 2024-08-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_patientmodel_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmodel',
            options={'ordering': ('-created_at',)},
        ),
    ]
