# Generated by Django 5.0.4 on 2024-09-02 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_patientmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
