# Generated by Django 5.1.1 on 2024-10-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_account_tg_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialtyTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctoraccountmodel',
            name='specialty_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.doctorspecialtytypemodel'),
        ),
    ]
