# Generated by Django 3.2 on 2022-10-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_rolesmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='organization_id',
            field=models.IntegerField(null=True),
        ),
    ]
