# Generated by Django 3.2 on 2022-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20221016_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
