# Generated by Django 3.2 on 2022-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialitymodel',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
