# Generated by Django 3.2.16 on 2022-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20221022_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
