# Generated by Django 3.2.16 on 2022-11-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_medicalservice_doctor'),
        ('account', '0016_alter_patientmodel_information_source'),
    ]

    operations = [
    ]
