# Generated by Django 3.2.16 on 2022-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_merge_20221112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
