# Generated by Django 3.2.16 on 2022-11-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_appointmentsmodel_end_time'),
        ('account', '0018_auto_20221112_1929'),
    ]

    operations = [
    ]
