# Generated by Django 3.2.16 on 2022-11-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_merge_20221119_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=255)),
                ('policy_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointmentsmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='appointmentservicemodel',
            name='branch',
        ),
        migrations.AddField(
            model_name='appointmentservicemodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='is_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='registrator_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentsmodel',
            name='send_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='exemption',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID'), ('CANCELLED', 'CANCELLED'), ('CANCELLED CANCELLED', 'CANCELLED CANCELLED')], default='NOT PAID', max_length=50),
        ),
    ]
