# Generated by Django 3.2.16 on 2022-11-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20221119_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservicemodel',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_services', to='account.appointmentsmodel'),
        ),
    ]
