# Generated by Django 3.2.16 on 2022-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_appointmentservicemodel_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentservicemodel',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
