# Generated by Django 3.2.16 on 2022-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_appointmentservicemodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='is_contract',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='is_priority',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='send_sms',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
