# Generated by Django 3.2.16 on 2022-11-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20221120_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentservicemodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='registrator_notes',
        ),
    ]
