# Generated by Django 3.2.16 on 2023-01-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_appointmentsmodel_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_at_work', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DoctorAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=300, null=True)),
                ('enc_otp', models.CharField(blank=True, max_length=300, null=True)),
                ('is_expired', models.SmallIntegerField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='appointmentsmodel',
            old_name='exemption',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='patientgroupmodel',
            old_name='exemption_percentage',
            new_name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='appointmentsmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='appointmentservicemodel',
            name='has_proceed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointmentservicemodel',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('NOT PAID', 'NOT PAID'), ('CANCELLED', 'CANCELLED'), ('CANCELLED CANCELLED', 'CANCELLED CANCELLED')], default='NOT PAID', max_length=50),
        ),
        migrations.AddField(
            model_name='appointmentservicemodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
