# Generated by Django 3.2.16 on 2023-01-07 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20230107_1259'),
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_appointments', to='cashbox.receiptmodel'),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoraccountmodel',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_model', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancemodel',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentsmodel',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to='account.doctoraccountmodel'),
        ),
        migrations.AlterField(
            model_name='doctorspecialitymodel',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_speciality', to='account.doctoraccountmodel'),
        ),
        migrations.AlterField(
            model_name='medicalservice',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='account.DoctorAccountModel'),
        ),
    ]
