# Generated by Django 3.2.16 on 2023-01-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20230107_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='is_manual',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
