# Generated by Django 3.2.16 on 2023-01-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_appointmentsmodel_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentsmodel',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
