# Generated by Django 5.0.4 on 2024-07-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0002_availableroommodel_availableroomstypemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroommodel',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_room', to='logus.availableroommodel'),
        ),
    ]
