# Generated by Django 5.1.1 on 2024-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_doctorspecialtytypemodel_and_more'),
        ('logus', '0012_tariffandmedicalservicematrixmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletariffmodel',
            name='medical_service',
            field=models.ManyToManyField(to='account.medicalservice'),
        ),
    ]
