# Generated by Django 5.1.1 on 2024-11-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0013_availabletariffmodel_medical_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TariffAndMedicalServiceMatrixModel',
        ),
    ]
