version: "3"

services:
  db:
    restart: unless-stopped
    image: postgres:15.0
    ports:
      - "5432:5432"
    volumes:
      - hayat_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hayat
      - POSTGRES_USER=hayat
      - POSTGRES_PASSWORD=hayat
  web:
    restart: unless-stopped
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_NAME=hayat
      - POSTGRES_USER=hayat
      - POSTGRES_PASSWORD=hayat
    depends_on:
      - db
volumes:
  hayat_db:
    driver: local