# Generated by Django 5.0.4 on 2024-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0008_alter_basepillsinjectionsmodel_pills_injections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baselabresearchservicemodel',
            name='model_ref_id',
        ),
        migrations.RemoveField(
            model_name='baselabresearchservicemodel',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='basemedicalservicemodel',
            name='model_ref_id',
        ),
        migrations.RemoveField(
            model_name='basemedicalservicemodel',
            name='model_type',
        ),
        migrations.RemoveField(
            model_name='baseprocedureservicemodel',
            name='model_ref_id',
        ),
        migrations.RemoveField(
            model_name='baseprocedureservicemodel',
            name='model_type',
        ),
    ]
