# Generated by Django 5.0.4 on 2024-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0009_remove_baselabresearchservicemodel_model_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprocedureservicemodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
