# Generated by Django 5.0.4 on 2024-09-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0012_finalappointmentwithdoctormodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalappointmentwithdoctormodel',
            name='arterial_high_low',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
