# Generated by Django 5.1.1 on 2024-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0015_consultingwithcardiologistmodel_arterial_high_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='heart_arterial_high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='heart_arterial_low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='imt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='imt_interpretation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
