# Generated by Django 5.1.1 on 2024-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0016_alter_consultingwithcardiologistmodel_heart_arterial_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentwithondutydoctormodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointmentwithondutydoctoronarrivalmodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
        migrations.AlterField(
            model_name='consultingwithcardiologistmodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
        migrations.AlterField(
            model_name='consultingwithneurologistmodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
        migrations.AlterField(
            model_name='ekgappointmentmodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
        migrations.AlterField(
            model_name='finalappointmentwithdoctormodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
        migrations.AlterField(
            model_name='repeatedappointmentwithdoctormodel',
            name='state',
            field=models.CharField(choices=[('Приём завершён', 'Приём завершён'), ('Пациент на прием не явился', 'Пациент на прием не явился'), ('Не завершено', 'Не завершено')], default='Приём завершён', max_length=250),
        ),
    ]
