# Generated by Django 5.1.1 on 2024-10-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0019_alter_appointmentwithondutydoctoronarrivalmodel_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatedappointmentwithdoctormodel',
            name='arterial_high_low',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
