# Generated by Django 5.1.1 on 2024-10-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0020_repeatedappointmentwithdoctormodel_arterial_high_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatedappointmentwithdoctormodel',
            name='imt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
