# Generated by Django 5.1.1 on 2024-10-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0022_appointmentwithondutydoctormodel_arterial_high_low_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentwithondutydoctormodel',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanatorium.diagnosistemplate'),
        ),
    ]
