# Generated by Django 5.1.1 on 2024-10-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0026_alter_labresult_base_lab_research'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='labresult',
            old_name='result',
            new_name='comments',
        ),
    ]
