# Generated by Django 5.1.1 on 2024-11-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0011_alter_bookingmodel_stage'),
        ('sanatorium', '0032_rename_quantity_basepillsinjectionsmodel_quantity_per_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesshistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_history', to='logus.bookingmodel'),
        ),
    ]
