# Generated by Django 5.1.1 on 2025-03-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0035_illnesshistory_is_sick_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illnesshistory',
            name='state',
            field=models.CharField(choices=[('registration', 'registration'), ('open', 'open'), ('closed', 'closed')], default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='initialappointmentwithdoctormodel',
            name='contact_with_infectious',
            field=models.TextField(blank=True, default='на протяжении максимального срока инкубации: не было', null=True),
        ),
    ]
