# Generated by Django 5.0.4 on 2024-06-08 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_itemsmodel_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomemodel',
            name='delivery_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.companymodel'),
        ),
    ]
