# Generated by Django 5.0.4 on 2024-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_incomeitemsmodel_overall_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendregistrymodel',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sentitemsmodel',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sentitemsmodel',
            name='state',
            field=models.CharField(choices=[('отменена', 'отменена'), ('не найдено', 'не найдено'), ('принято', 'принято')], default='принято', max_length=50),
        ),
    ]
