# Generated by Django 5.0.4 on 2024-06-18 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_sendregistrymodel_series_sentitemsmodel_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitemsmodel',
            name='send_registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_registry_items', to='warehouse.sendregistrymodel'),
        ),
    ]
