# Generated by Django 5.0.4 on 2024-06-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_sendregistrymodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitemsmodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('отменена', 'отменена'), ('не найдено', 'не найдено'), ('принято', 'принято')], default='принято', max_length=50),
        ),
    ]
