# Generated by Django 5.0.4 on 2024-06-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_itemsinstockmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitemsmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_registry_items', to='warehouse.itemsmodel'),
        ),
    ]
