# Generated by Django 5.0.4 on 2024-06-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_alter_sentitemsmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousechequemodel',
            name='state',
            field=models.CharField(choices=[('оплачено', 'оплачено'), ('отменена', 'отменена'), ('не оплачено', 'не оплачено')], default='не оплачено', max_length=50),
        ),
    ]
