# Generated by Django 5.0.4 on 2024-06-23 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_warehousechequemodel_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='filial',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='store_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.storepointmodel'),
        ),
    ]
