# Generated by Django 5.0.4 on 2024-06-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_expensemodel_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitemsmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanse_items', to='warehouse.itemsmodel'),
        ),
    ]
