# Generated by Django 5.0.4 on 2024-06-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_alter_expenseitemsmodel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitemsmodel',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanse_items', to='warehouse.expensemodel'),
        ),
    ]
