# Generated by Django 5.0.4 on 2024-06-23 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_expenseitemsmodel_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepointstaffmodel',
            name='staff',
        ),
        migrations.AddField(
            model_name='storepointstaffmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
