# Generated by Django 5.0.4 on 2024-06-23 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_remove_storepointstaffmodel_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storepointstaffmodel',
            unique_together={('staff', 'store_point')},
        ),
    ]
