# Generated by Django 5.0.4 on 2024-06-29 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_rename_main_storepointmodel_is_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incomemodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('принято', 'принято'), ('отказоно', 'отказоно')], default='принято', max_length=50),
        ),
        migrations.AlterField(
            model_name='storepointstaffmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
