# Generated by Django 5.0.4 on 2024-07-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0025_alter_expenseitemsmodel_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsinstockmodel',
            options={'ordering': ('-expire_date',)},
        ),
        migrations.AlterUniqueTogether(
            name='itemsinstockmodel',
            unique_together={('item', 'warehouse')},
        ),
    ]
