# Generated by Django 5.0.4 on 2024-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0028_alter_sentitemsmodel_state_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsinstockmodel',
            options={'ordering': ('expire_date',)},
        ),
        migrations.AddField(
            model_name='storepointmodel',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
