# Generated by Django 5.0.4 on 2024-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0030_alter_itemsinstockmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinstockmodel',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemsinstockmodel',
            name='unit_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
