# Generated by Django 5.0.4 on 2024-07-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0031_itemsinstockmodel_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='price',
        ),
    ]
