# Generated by Django 5.0.4 on 2024-07-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0032_remove_itemsmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.itemsinstockmodel'),
        ),
    ]
