# Generated by Django 5.0.4 on 2024-07-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0036_chequeitemsmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeitemsmodel',
            name='unit_price',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomeitemsmodel',
            name='unit_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
