# Generated by Django 5.0.4 on 2024-07-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0037_incomeitemsmodel_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentitemsmodel',
            name='unit_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
