# Generated by Django 5.0.4 on 2024-08-11 08:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0038_sentitemsmodel_unit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='serial',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
