# Generated by Django 5.1.1 on 2024-11-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0041_remove_expenseitemsmodel_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousechequemodel',
            name='is_sanatorium_based',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
