# Generated by Django 5.1.1 on 2024-11-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0043_warehousechequemodel_illness_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='frequency',
            field=models.CharField(choices=[('3 раза в день', 3), ('до еды', 1), ('после еды', 1)], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='state',
            field=models.CharField(choices=[('assigned', 'assigned'), ('cancelled', 'cancelled'), ('stopped', 'stopped'), ('dispatched', 'dispatched')], default='assigned', max_length=50),
        ),
    ]
