# Generated by Django 5.1.1 on 2024-11-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0045_alter_chequeitemsmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='quantity_per_session',
            field=models.IntegerField(default=1),
        ),
    ]
