# Generated by Django 5.1.1 on 2024-11-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0046_chequeitemsmodel_quantity_per_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='quantity_per_session',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
