# Generated by Django 5.1.1 on 2024-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0047_alter_chequeitemsmodel_quantity_per_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='frequency',
            field=models.CharField(choices=[('3 раза в день', '3 раза в день'), ('до еды', 'до еды'), ('после еды', 'после еды')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='state',
            field=models.CharField(choices=[('assigned', 'assigned'), ('accepted', 'accepted'), ('cancelled', 'cancelled'), ('stopped', 'stopped'), ('dispatched', 'dispatched')], default='assigned', max_length=50),
        ),
    ]
