# Generated by Django 5.0.4 on 2024-06-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lis', '0002_remove_orderedlabresearchmodel_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedlabresearchmodel',
            name='order_status',
            field=models.CharField(choices=[('готово', 'Done'), ('в процессе', 'In Progress'), ('отменена', 'Cancelled'), ('готовые но не распечатан', 'Not Printed'), ('распечатан', 'Printed')], default='в процессе', max_length=255),
        ),
    ]
