# Generated by Django 5.0.4 on 2024-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsmodel',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='itemsinstockmodel',
            name='expire_date',
            field=models.DateField(null=True),
        ),
    ]
