# Generated by Django 5.0.4 on 2024-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_incomemodel_delivery_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomemodel',
            name='bill_amount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
