# Generated by Django 5.0.4 on 2024-06-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_incomemodel_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeitemsmodel',
            name='overall_price',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='incomeitemsmodel',
            name='price',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
