# Generated by Django 5.0.4 on 2024-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_alter_sentitemsmodel_send_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendregistrymodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('доставлено', 'доставлено'), ('отказоно', 'отказоно')], default='в ожидании', max_length=50),
        ),
    ]
