# Generated by Django 5.0.4 on 2024-06-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_storepointrolesmodel_storepointstaffmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinstockmodel',
            name='income_registry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.incomemodel'),
        ),
    ]
