# Generated by Django 5.0.4 on 2024-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_remove_expensemodel_filial_expensemodel_store_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitemsmodel',
            name='expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expenseitemsmodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('отменена', 'отменена'), ('не найдено', 'не найдено'), ('принято', 'принято')], default='принято', max_length=50),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('доставлено', 'доставлено'), ('отказоно', 'отказоно')], default='в ожидании', max_length=50),
        ),
    ]
