# Generated by Django 5.0.4 on 2024-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_expenseitemsmodel_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
