# Generated by Django 5.0.4 on 2024-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_alter_storepointstaffmodel_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storepointmodel',
            old_name='main',
            new_name='is_main',
        ),
    ]
