# Generated by Django 5.0.4 on 2024-07-06 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0024_incomemodel_state_alter_storepointstaffmodel_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitemsmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanse_items', to='warehouse.itemsinstockmodel'),
        ),
    ]
