# Generated by Django 5.0.4 on 2024-07-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0026_alter_itemsinstockmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitemsmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_registry_items', to='warehouse.itemsinstockmodel'),
        ),
    ]
