# Generated by Django 5.0.4 on 2024-07-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0027_alter_sentitemsmodel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentitemsmodel',
            name='state',
            field=models.CharField(choices=[('в ожидании', 'в ожидании'), ('отменена', 'отменена'), ('не найдено', 'не найдено'), ('принято', 'принято')], default='в ожидании', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='itemsinstockmodel',
            unique_together={('item', 'warehouse', 'expire_date', 'income_registry', 'income_seria')},
        ),
    ]
