# Generated by Django 5.0.4 on 2024-07-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0029_alter_itemsinstockmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsinstockmodel',
            unique_together={('item', 'warehouse', 'expire_date', 'income_seria')},
        ),
        migrations.RemoveField(
            model_name='itemsinstockmodel',
            name='income_registry',
        ),
    ]
