# Generated by Django 5.0.4 on 2024-07-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0033_alter_chequeitemsmodel_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsinstockmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', to='warehouse.itemsmodel'),
        ),
        migrations.DeleteModel(
            name='ChequeItemsModel',
        ),
    ]
