# Generated by Django 5.0.4 on 2024-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0035_chequeitemsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeitemsmodel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
