# Generated by Django 5.0.4 on 2024-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0039_alter_incomemodel_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeitemsmodel',
            name='nds',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
