# Generated by Django 5.0.4 on 2024-08-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0040_incomeitemsmodel_nds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitemsmodel',
            name='expire_date',
        ),
    ]
