# Generated by Django 5.1.1 on 2024-11-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanatorium', '0031_labresult_file_format_alter_proceduredaysmodel_state'),
        ('warehouse', '0042_warehousechequemodel_is_sanatorium_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousechequemodel',
            name='illness_history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_cheque', to='sanatorium.illnesshistory'),
        ),
    ]
