# Generated by Django 5.1.1 on 2024-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0044_chequeitemsmodel_comments_chequeitemsmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chequeitemsmodel',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
