# Generated by Django 5.0.4 on 2024-05-30 15:34

import apps.lis.models.containers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('color_hex', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.lis.models.containers.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LabMeasurementUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('is_archive', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('is_aliquoted', models.BooleanField(default=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('nomenclature_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lis.containercolormodel')),
                ('container_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lis.containergroupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LabResearchCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branchmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LabResearchSubCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='lis.labresearchcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='LabResearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.BigIntegerField(default=100)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_code', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.IntegerField(blank=True, null=True)),
                ('deadline_cito', models.IntegerField(blank=True, null=True)),
                ('cito', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branchmodel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_research', to='lis.labresearchcategorymodel')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_research', to='lis.labresearchsubcategorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='LabResearchTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('result_type', models.CharField(blank=True, choices=[('строковый', 'строковый'), ('числовой', 'числовой')], max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('ignore_status', models.BooleanField(default=False)),
                ('is_required_print_result', models.BooleanField(default=True)),
                ('instruments', models.CharField(blank=True, max_length=255, null=True)),
                ('keyboard', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_result', models.CharField(blank=True, max_length=255, null=True)),
                ('default_result', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_code', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_code_for_repeat', models.CharField(blank=True, max_length=255, null=True)),
                ('is_micro_organism', models.BooleanField(default=False)),
                ('id_test_system', models.CharField(blank=True, max_length=255, null=True)),
                ('name_test_system', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lis.labmeasurementunitmodel')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_research_test', to='lis.labresearchmodel')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lis.labtestgroupmodel')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lis.labtestmethodmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LabWorkingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_working_stations', to='account.branchmodel')),
            ],
        ),
        migrations.AddField(
            model_name='labresearchmodel',
            name='backup_working_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_backup_w_s', to='lis.labworkingstation'),
        ),
        migrations.AddField(
            model_name='labresearchmodel',
            name='main_working_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_main_w_s', to='lis.labworkingstation'),
        ),
        migrations.CreateModel(
            name='OrderedLabResearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=255)),
                ('container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cito', models.BooleanField(default=False)),
                ('staging', models.CharField(blank=True, max_length=255, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('queue_number', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_assistant_comment', models.TextField(blank=True, null=True)),
                ('expected_date', models.CharField(blank=True, max_length=255, null=True)),
                ('pathology', models.BooleanField(default=True)),
                ('payment_status', models.CharField(blank=True, choices=[('оплачено', 'оплачено'), ('не оплачено', 'не оплачено'), ('отменена', 'отменена')], max_length=255, null=True)),
                ('order_status', models.CharField(choices=[('готово', 'готово'), ('в процессе', 'в процессе'), ('отменена', 'отменена')], default='в процессе', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.branchmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='registered_by')),
                ('delivery_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_delivery_point', to='account.branchmodel')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_lab_research', to='lis.labresearchmodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modf_cart_lab_research', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.patientmodel')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_cart_lab_research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_code', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.TextField()),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('выше нормы', 'выше нормы'), ('в норме', 'в норме'), ('отменена', 'отменена')], max_length=255, null=True)),
                ('test_status', models.CharField(choices=[('готово', 'готово'), ('в процессе', 'в процессе'), ('отменена', 'отменена')], default='в процессе', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lis.containermodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='registered_by')),
                ('lab_research_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lis.labresearchtestmodel')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modf_cart_lab_test', to=settings.AUTH_USER_MODEL)),
                ('ordered_lab_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='lis.orderedlabresearchmodel')),
            ],
        ),
    ]
