# Generated by Django 5.0.4 on 2024-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedlabresearchmodel',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='orderedlabresearchmodel',
            name='validate_status',
            field=models.CharField(blank=True, choices=[('Невалидированные(Зеленые)', 'Green'), ('Валидированные(Синие)', 'Blue'), ('Неготовые(Черные)', 'Black'), ('Все', 'All'), ('Не готовые + Невалидированные', 'Not Ready'), ('Вне нормы', 'Unnorm'), ('Просроченные по постановке', 'Expired'), ('Просроченные по готовности', 'Expired2'), ('Просроченные по валидации', 'Expired3'), ('Не готовые, но с результатами', 'With Results')], max_length=50, null=True),
        ),
    ]
