# Generated by Django 3.2.16 on 2023-01-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashboxclosinghistoryrecordsmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='operationist'),
        ),
        migrations.CreateModel(
            name='DutyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modf_duty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CASHBOX| 1. Duty',
                'verbose_name_plural': 'CASHBOX| 1. Duty',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbox.dutymodel'),
        ),
    ]
