# Generated by Django 5.0.4 on 2024-07-25 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=False)),
                ('floor', models.IntegerField(default=1)),
                ('view', models.CharField(choices=[('residential', 'residential'), ('mountains', 'mountains'), ('river', 'river')], default='residential', max_length=200)),
                ('capacity', models.IntegerField()),
                ('status_cleanest', models.CharField(choices=[('clean', 'clean'), ('dirty', 'dirty')], default='clean', max_length=30)),
                ('room_task_type', models.CharField(choices=[('living', 'living'), ('service', 'service'), ('security', 'security')], default='living', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableRoomsTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTypeMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_room', to='logus.availableroommodel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='logus.availableroomstypemodel')),
            ],
        ),
    ]
