# Generated by Django 5.0.4 on 2024-07-31 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0005_alter_bookingmodel_current_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_history_type', to='logus.availableroomstypemodel'),
        ),
    ]
