# Generated by Django 5.0.4 on 2024-08-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0007_availabletariffmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffRoomTypeMatrixModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.ManyToManyField(blank=True, null=True, to='logus.availableroomstypemodel')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='logus.availabletariffmodel')),
            ],
        ),
    ]
