# Generated by Django 5.0.4 on 2024-08-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0009_tariffroomtypematrixmodel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_history_tariff', to='logus.availabletariffmodel'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='current_tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_tariff', to='logus.availabletariffmodel'),
        ),
    ]
