# Generated by Django 5.0.4 on 2024-08-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0010_alter_bookinghistory_tariff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='stage',
            field=models.CharField(choices=[('booked', 'booked'), ('settled', 'settled'), ('arrived', 'arrived'), ('cancelled', 'cancelled'), ('served', 'served')], default='booked', max_length=10),
        ),
    ]
