# Generated by Django 5.1.1 on 2024-11-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_doctorspecialtytypemodel_and_more'),
        ('logus', '0011_alter_bookingmodel_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffAndMedicalServiceMatrixModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_service', models.ManyToManyField(to='account.medicalservice')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='included_med_services', to='logus.availabletariffmodel')),
            ],
        ),
    ]
