# Generated by Django 5.1.1 on 2024-11-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0014_delete_tariffandmedicalservicematrixmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='with_companion',
            field=models.BooleanField(default=False),
        ),
    ]
