# Generated by Django 5.1.1 on 2024-11-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0015_bookingmodel_with_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='booked_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='logus.bookingmodel'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('singular', 'singular'), ('whole_check', 'whole_check')], default='singular', max_length=50),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pocket_type',
            field=models.CharField(blank=True, choices=[('additional service', 'additional service'), ('room', 'room'), ('tariff', 'tariff'), ('medicine', 'medicine'), ('fee', 'fee')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('humo', 'humo'), ('uzcard', 'uzcard'), ('payme', 'payme'), ('click', 'click'), ('uzum', 'uzum')], default='cash', max_length=50),
        ),
    ]
