# Generated by Django 5.1.1 on 2024-11-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logus', '0016_alter_payments_booked_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_type',
            field=models.CharField(choices=[('Наличка', 'Наличка'), ('humo', 'humo'), ('uzcard', 'uzcard'), ('payme', 'payme'), ('click', 'click'), ('uzum', 'uzum')], default='Наличка', max_length=50),
        ),
    ]
