# Generated by Django 5.1.1 on 2024-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_nurseaccountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tg_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
