# Generated by Django 5.1.1 on 2025-01-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_doctorspecialtytypemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservice',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='med_service_specialty', to='account.specialitymodel'),
        ),
    ]
