# Generated by Django 5.1.1 on 2025-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_medicalservice_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_therapist',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
